package com.ws101.Alastoy_Espano.EcommerceApi.model;

import jakarta.persistence.*;
import lombok.*;
import java.util.List;

/**
 * Represents a product category.
 * One category can have many products.
 *
 * @author Alastoy, Españo
 */
@Entity
@Table(name = "categories")
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
@ToString
@EqualsAndHashCode

public class Category {

    /**
     * The category ID. Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The category name.
     */
    @Column(nullable = false, unique = true)
    private String name;

    /**
     * List of products belonging to this category.
     * One category has many products.
     */
    @OneToMany(mappedBy = "category", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @ToString.Exclude
    @EqualsAndHashCode.Exclude
    private List<Product> products;
}
