package com.ws101.Alastoy_Espano.EcommerceApi.model;

import jakarta.persistence.*;
import lombok.*;

/**
 * Represents a product in the store.
 *
 * @author Alastoy, Españo
 */
@Entity
@Table(name = "products")
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
@ToString
@EqualsAndHashCode

public class Product {

    /**
     * The product ID. Auto-generated by the database
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The product name.
     */
    @Column(nullable = false)
    private String name;

    /**
     * The product description.
     */
    private String description;

    /**
     * The product price.
     */
    private double price;

    /**
     * The product category. Many products belong to one category.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id")
    private Category category;

    /**
     * The available stock quantity.
     */
    private Integer stockQuantity;

    /**
     * The URL of the product image.
     */
    private String imageUrl;
}
